//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUrenRegistratie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrenregistratieEntities : DbContext
    {
        public UrenregistratieEntities()
            : base("name=UrenregistratieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Projecten> Projecten { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Taken> Taken { get; set; }
        public DbSet<Uren> Uren { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersProjectenLijst> UsersProjectenLijst { get; set; }
    }
}
