//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUrenRegistratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projecten
    {
        public Projecten()
        {
            this.Taken = new HashSet<Taken>();
            this.UsersProjectenLijst = new HashSet<UsersProjectenLijst>();
        }
    
        public int projectId { get; set; }
        public string projectNaam { get; set; }
        public string projectOmschrijving { get; set; }
        public System.DateTime beginDatum { get; set; }
        public Nullable<System.DateTime> eindDatum { get; set; }
        public bool afgesloten { get; set; }
    
        public virtual ICollection<Taken> Taken { get; set; }
        public virtual ICollection<UsersProjectenLijst> UsersProjectenLijst { get; set; }
    }
}
