//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUrenRegistratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uren
    {
        public int urenId { get; set; }
        public int userProjectId { get; set; }
        public int userId { get; set; }
        public int projectId { get; set; }
        public int takenId { get; set; }
        public System.DateTime datum { get; set; }
        public int uren1 { get; set; }
        public string urenVerantwoording { get; set; }
    
        public virtual UsersProjectenLijst UsersProjectenLijst { get; set; }
    }
}
