//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUrenRegistratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersProjectenLijst
    {
        public UsersProjectenLijst()
        {
            this.Uren = new HashSet<Uren>();
        }
    
        public int userProjectId { get; set; }
        public int projectId { get; set; }
        public int userId { get; set; }
        public int takenId { get; set; }
    
        public virtual Projecten Projecten { get; set; }
        public virtual Taken Taken { get; set; }
        public virtual ICollection<Uren> Uren { get; set; }
        public virtual Users Users { get; set; }
    }
}
