//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_ERF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorieën
    {
        public Categorieën()
        {
            this.Subcategorieën = new HashSet<Subcategorieën>();
        }
    
        public int CategorieID { get; set; }
        public string Categorienaam { get; set; }
        public int Score { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual ICollection<Subcategorieën> Subcategorieën { get; set; }
    }
}
