//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_ERF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PVB_MOF_ERDEntities : DbContext
    {
        public PVB_MOF_ERDEntities()
            : base("name=PVB_MOF_ERDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Categorieën> Categorieën { get; set; }
        public DbSet<Sessies> Sessies { get; set; }
        public DbSet<Subcategorieën> Subcategorieën { get; set; }
        public DbSet<Images> IMAGES { get; set; }
    }
}
