//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_ERF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageBinary { get; set; }
    }
}
