//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_ERF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessies
    {
        public System.DateTime Datum { get; set; }
        public int Aantal { get; set; }
    }
}
