//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVB_ERF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategorieën
    {
        public int SubcategorieID { get; set; }
        public int CategorieID { get; set; }
        public string Subcategorienaam { get; set; }
        public int Score { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Categorieën Categorieën { get; set; }
    }
}
