//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToetsendRekenen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Gebruikersnaam { get; set; }
        public string Wachtwoord { get; set; }
    }
}
